import type { Metadata } from "next";
import "@fontsource-variable/inter";
import "./globals.css";
import "@fontsource-variable/mona-sans";
import "@fontsource-variable/vollkorn";
import Navbar from "./components/NavBar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black text-white">
      <body className="]">
        <Navbar />

        {children}
      </body>
    </html>
  );
}
